---
- name: list deploypath
  shell: ls -1 /opt/tomcat/webapps/
  register: contents
- name: remove
  file: 
    path: /opt/tomcat/webapps/{{ item }} 
    state: absent
  with_items: "{{ contents.stdout_lines }}"

- name: deploy war file
  get_url:
    url: http://35.154.218.167:8081/repository/mohan-group/org/springframework/samples/spring-framework-petclinic/{{ version }}/spring-framework-petclinic-{{ version }}.war
    dest: /opt/tomcat/webapps/petclinic.war
    username: "{{ nexususer }}"
    password: "{{ nexuspassword }}"
